dependencies {
    implementation project(':simpleec-common')
    implementation project(':simpleec-core')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'io.lettuce:lettuce-core'
}

bootJar {
    mainClass = 'com.simpleec.schedulerjob.SchedulerJobApplication'
}
