dependencies {
    implementation project(':simpleec-common')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'io.lettuce:lettuce-core'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

tasks.named('bootJar') {
    enabled = true
    mainClass = 'com.simpleec.schedulerjob.SchedulerJobApplication'
}
