-- =============================================================================
-- SimpleEC OMS — Database Schema
-- Version: v4 (2026-02-09)
-- Source of truth: docs/SCHEMA.md
--
-- PK Rule: All tables use VARCHAR(20) NanoID generated by application code.
-- No BIGSERIAL / auto-increment.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. platform_account — SimpleEC platform admin (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.platform_account (
    id              VARCHAR(20)   NOT NULL,
    name            VARCHAR(50)   NOT NULL,
    email           VARCHAR(256)  NOT NULL,
    password        VARCHAR(512)  NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT platform_account_email UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- 2. global_config — System settings (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.global_config (
    id          VARCHAR(128)   NOT NULL,
    data        VARCHAR(2048)  NOT NULL,
    description VARCHAR(256),
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- 3. merchant — Tenant / company (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.merchant (
    id                    VARCHAR(20)  NOT NULL,
    merchant_name         VARCHAR(256) NOT NULL,
    merchant_email        VARCHAR(256) NOT NULL,
    merchant_phone_number VARCHAR(20)  NOT NULL,
    tax_id_number         VARCHAR(20)  NOT NULL,
    address_city          VARCHAR(50)  NOT NULL,
    address_region        VARCHAR(50)  NOT NULL,
    address_country       VARCHAR(50)  NOT NULL,
    address_zip           VARCHAR(10)  NOT NULL,
    address_phone_number  VARCHAR(20)  NOT NULL,
    address_line1         VARCHAR(256) NOT NULL,
    address_line2         VARCHAR(256) NOT NULL,
    vip_level             INTEGER      NOT NULL DEFAULT 0,
    user_local_time_zone  VARCHAR(50)  NOT NULL DEFAULT 'UTC',
    payer_name            VARCHAR(256) NOT NULL,
    payer_email           VARCHAR(256) NOT NULL,
    payer_phone_number    VARCHAR(20)  NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- 4. account — Merchant operator accounts (FK → merchant)
-- ---------------------------------------------------------------------------
CREATE TABLE public.account (
    id               VARCHAR(20)  NOT NULL,
    account_name     VARCHAR(256) NOT NULL,
    account_email    VARCHAR(256) NOT NULL,
    account_password VARCHAR(512) NOT NULL,
    account_tel      VARCHAR(20),
    is_main_account  BOOLEAN      NOT NULL DEFAULT false,
    access_level     INTEGER      NOT NULL DEFAULT 0,
    merchant_id      VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'enable',
    totp_secret      VARCHAR(20),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT account_email_un UNIQUE (account_email),
    CONSTRAINT fk_account_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- ---------------------------------------------------------------------------
-- 5. merchant_options — Merchant custom options (FK → merchant)
-- ---------------------------------------------------------------------------
CREATE TABLE public.merchant_options (
    id              VARCHAR(20)  NOT NULL,
    merchant_id     VARCHAR(20)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'enable',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_merchant_options_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- ---------------------------------------------------------------------------
-- 6. platform — E-commerce platforms (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.platform (
    id               VARCHAR(20)   NOT NULL,
    platform_name    VARCHAR(50)   NOT NULL,
    credential1      VARCHAR(4096),
    credential2      VARCHAR(4096),
    actived          BOOLEAN       NOT NULL DEFAULT true,
    queue_topic      VARCHAR(128),
    currency         VARCHAR(3)    DEFAULT 'TWD',
    ship_options     JSON,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- 7. channel_api_versions — Platform API version management (FK → platform)
-- ---------------------------------------------------------------------------
CREATE TABLE public.channel_api_versions (
    id             VARCHAR(20)  NOT NULL,
    platform_id    VARCHAR(20)  NOT NULL,
    api_version    VARCHAR(20)  NOT NULL,
    is_active      BOOLEAN      NOT NULL DEFAULT true,
    effective_date DATE,
    description    TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_api_version_platform FOREIGN KEY (platform_id)
        REFERENCES public.platform (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- ---------------------------------------------------------------------------
-- 8. channel — Channel / store (pivot: FK → platform + merchant)
-- ---------------------------------------------------------------------------
CREATE TABLE public.channel (
    id                    VARCHAR(20)   NOT NULL,
    platform_id           VARCHAR(20)   NOT NULL,
    merchant_id           VARCHAR(20)   NOT NULL,
    channel_sn            VARCHAR(128),
    channel_name          VARCHAR(256),
    multi_spec            BOOLEAN       NOT NULL DEFAULT false,
    token                 VARCHAR(4096) NOT NULL,
    token2                VARCHAR(4096),
    token3                VARCHAR(4096),
    token4                VARCHAR(4096),
    token5                VARCHAR(4096),
    actived               BOOLEAN       NOT NULL DEFAULT true,
    write_actived         BOOLEAN       NOT NULL DEFAULT false,
    enable_sync           BOOLEAN       NOT NULL DEFAULT false,
    first_sync_start_time TIMESTAMPTZ,
    first_sync_end_time   TIMESTAMPTZ,
    last_sync_time        TIMESTAMPTZ,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_channel_platform FOREIGN KEY (platform_id)
        REFERENCES public.platform (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_channel_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- ---------------------------------------------------------------------------
-- 8b. channel_shipping_mapping — Shipping method mapping per channel
-- ---------------------------------------------------------------------------
CREATE TABLE public.channel_shipping_mapping (
    id                          VARCHAR(20)   NOT NULL,
    merchant_id                 VARCHAR(20)   NOT NULL,
    channel_id                  VARCHAR(20)   NOT NULL,
    platform_shipping_method    VARCHAR(100)  NOT NULL,
    logistics_company           VARCHAR(100)  NOT NULL,
    logistics_company_code      VARCHAR(50),
    description                 VARCHAR(256),
    active                      BOOLEAN       NOT NULL DEFAULT true,
    created_at                  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_shipping_map_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_shipping_map_channel FOREIGN KEY (channel_id)
        REFERENCES public.channel (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT uk_shipping_map UNIQUE (channel_id, platform_shipping_method)
);

CREATE INDEX idx_shipping_map_channel ON public.channel_shipping_mapping (channel_id);
CREATE INDEX idx_shipping_map_merchant ON public.channel_shipping_mapping (merchant_id);

-- ---------------------------------------------------------------------------
-- 9. product_group — Product group for frontend management (FK → merchant)
-- ---------------------------------------------------------------------------
CREATE TABLE public.product_group (
    id             VARCHAR(20)  NOT NULL,
    merchant_id    VARCHAR(20)  NOT NULL,
    group_name     VARCHAR(512) NOT NULL,
    description    TEXT,
    brand          VARCHAR(100),
    main_image_url VARCHAR(1024),
    status         VARCHAR(20)  NOT NULL DEFAULT 'active',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_product_group_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE INDEX idx_product_group_merchant ON public.product_group (merchant_id);

-- ---------------------------------------------------------------------------
-- 10. product — Product = SKU level (FK → merchant, product_group)
-- ---------------------------------------------------------------------------
CREATE TABLE public.product (
    id               VARCHAR(20)   NOT NULL,
    merchant_id      VARCHAR(20)   NOT NULL,
    product_group_id VARCHAR(20),
    sku              VARCHAR(100)  NOT NULL,
    name             VARCHAR(512)  NOT NULL,
    spec_summary     VARCHAR(256),
    cost_price       DECIMAL(12,2),
    suggest_price    DECIMAL(12,2),
    quantity         INTEGER       NOT NULL DEFAULT 0,
    safety_quantity  INTEGER       NOT NULL DEFAULT 0,
    status           VARCHAR(20)   NOT NULL DEFAULT 'active',
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_product_merchant FOREIGN KEY (merchant_id)
        REFERENCES public.merchant (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_product_group FOREIGN KEY (product_group_id)
        REFERENCES public.product_group (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_product_merchant_sku ON public.product (merchant_id, sku);
CREATE INDEX idx_product_merchant_status ON public.product (merchant_id, status);
CREATE INDEX idx_product_group ON public.product (product_group_id);

-- ---------------------------------------------------------------------------
-- 11. product_barcode — Multiple barcodes per product (FK → product)
-- ---------------------------------------------------------------------------
CREATE TABLE public.product_barcode (
    id          VARCHAR(20)  NOT NULL,
    product_id  VARCHAR(20)  NOT NULL,
    barcode     VARCHAR(50)  NOT NULL,
    label       VARCHAR(100),
    is_primary  BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_barcode_product FOREIGN KEY (product_id)
        REFERENCES public.product (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_barcode_product ON public.product_barcode (product_id);
CREATE INDEX idx_barcode_value ON public.product_barcode (barcode);

-- ---------------------------------------------------------------------------
-- 12. sell_pack — Listing mapping (product x channel) (FK → product, channel)
-- ---------------------------------------------------------------------------
CREATE TABLE public.sell_pack (
    id                   VARCHAR(20)   NOT NULL,
    merchant_id          VARCHAR(20)   NOT NULL,
    product_id           VARCHAR(20)   NOT NULL,
    channel_id           VARCHAR(20)   NOT NULL,
    sku                  VARCHAR(100)  NOT NULL,
    channel_product_id   VARCHAR(256),
    channel_spec_id      VARCHAR(256),
    channel_product_name VARCHAR(512),
    channel_spec_name    VARCHAR(256),
    channel_product_url  VARCHAR(1024),
    title                VARCHAR(512),
    channel_spec_attrs   JSONB,                  -- 通路特定的規格屬性（如 {color: 紅色, size: M}）
    selling_price        DECIMAL(12,2),
    quantity             INTEGER       NOT NULL DEFAULT 0,
    status               VARCHAR(20)   NOT NULL DEFAULT 'draft',
    visibility           VARCHAR(20),            -- 通路上的可見性（VISIBLE, HIDDEN）
    last_sync_at         TIMESTAMPTZ,
    sync_status          JSONB,                  -- 同步狀態追蹤（pending|syncing|completed|failed）
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_sellpack_product FOREIGN KEY (product_id)
        REFERENCES public.product (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_sellpack_channel FOREIGN KEY (channel_id)
        REFERENCES public.channel (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE INDEX idx_sellpack_merchant ON public.sell_pack (merchant_id);
CREATE INDEX idx_sellpack_channel ON public.sell_pack (channel_id);
CREATE INDEX idx_sellpack_product ON public.sell_pack (product_id);
CREATE INDEX idx_sellpack_sku ON public.sell_pack (sku);
-- Unique Key: 同一個 channel + 同一個 spec (規格) + 同一個 sku (通路 SKU/賣編)
-- 允許同一個 product 在同一個 channel 上重複上架（不同規格/SKU 組合）
CREATE UNIQUE INDEX idx_sellpack_upsert_key
    ON public.sell_pack (channel_id, channel_spec_id, sku);

-- ---------------------------------------------------------------------------
-- 13. orders — Orders with JSONB items (FK → channel)
-- ---------------------------------------------------------------------------
CREATE TABLE public.orders (
    id                 VARCHAR(20)   NOT NULL,
    merchant_id        VARCHAR(20)   NOT NULL,
    channel_id         VARCHAR(20)   NOT NULL,
    channel_order_id     VARCHAR(100)  NOT NULL,
    channel_order_number VARCHAR(100),
    order_status         VARCHAR(20)   NOT NULL DEFAULT 'pending',
    buyer_name         VARCHAR(512),
    buyer_phone        VARCHAR(256),
    buyer_email        VARCHAR(512),
    buyer_info         JSONB,
    shipping_address   TEXT,
    shipping_method    VARCHAR(50),
    shipping_info      JSONB,
    payment_method     VARCHAR(50),
    total_amount       DECIMAL(12,2) NOT NULL DEFAULT 0,
    shipping_fee       DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
    items              JSONB         NOT NULL DEFAULT '[]',
    is_rollback        BOOLEAN       NOT NULL DEFAULT false,
    channel_created_at TIMESTAMPTZ,
    paid_at            TIMESTAMPTZ,
    shipped_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_order_channel FOREIGN KEY (channel_id)
        REFERENCES public.channel (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE UNIQUE INDEX idx_order_channel_order ON public.orders (channel_id, channel_order_id);
CREATE INDEX idx_order_merchant_status ON public.orders (merchant_id, order_status);
CREATE INDEX idx_order_created ON public.orders (created_at DESC);
CREATE INDEX idx_order_items ON public.orders USING GIN (items);

-- ---------------------------------------------------------------------------
-- 14. order_status_logs — Order status change history (FK → orders)
-- ---------------------------------------------------------------------------
CREATE TABLE public.order_status_logs (
    id          VARCHAR(20)  NOT NULL,
    order_id    VARCHAR(20)  NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    operator    VARCHAR(100),
    remark      TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_status_log_order FOREIGN KEY (order_id)
        REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_order_status_log_order ON public.order_status_logs (order_id);

-- ---------------------------------------------------------------------------
-- 15. order_shipments — Shipment tracking (FK → orders)
-- ---------------------------------------------------------------------------
CREATE TABLE public.order_shipments (
    id                VARCHAR(20)  NOT NULL,
    order_id          VARCHAR(20)  NOT NULL,
    tracking_number   VARCHAR(100),
    logistics_company VARCHAR(100),
    shipping_status   VARCHAR(20)  NOT NULL DEFAULT 'pending',
    shipped_at        TIMESTAMPTZ,
    delivered_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_shipment_order FOREIGN KEY (order_id)
        REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_shipment_order ON public.order_shipments (order_id);
CREATE INDEX idx_shipment_tracking ON public.order_shipments (tracking_number);

-- ---------------------------------------------------------------------------
-- 16. refund_orders — Refund orders with JSONB items (FK → orders)
-- ---------------------------------------------------------------------------
CREATE TABLE public.refund_orders (
    id                VARCHAR(20)   NOT NULL,
    order_id          VARCHAR(20)   NOT NULL,
    merchant_id       VARCHAR(20)   NOT NULL,
    channel_refund_id VARCHAR(100),
    refund_status     VARCHAR(20)   NOT NULL DEFAULT 'pending',
    refund_amount     DECIMAL(12,2) NOT NULL DEFAULT 0,
    reason            TEXT,
    requested_at      TIMESTAMPTZ,               -- 退貨申請時間（來自通路）
    items             JSONB         DEFAULT '[]',
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_refund_order FOREIGN KEY (order_id)
        REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE INDEX idx_refund_order ON public.refund_orders (order_id);
CREATE INDEX idx_refund_merchant ON public.refund_orders (merchant_id);

-- ---------------------------------------------------------------------------
-- 17. channel_sync_logs — Sync / health check logs (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.channel_sync_logs (
    id               VARCHAR(20)  NOT NULL,
    merchant_id      VARCHAR(20)  NOT NULL,
    channel_id       VARCHAR(20)  NOT NULL,
    sync_type        VARCHAR(50)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'success',
    health           VARCHAR(20),
    request_payload  TEXT,
    response_payload TEXT,
    error_message    TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_sync_log_channel ON public.channel_sync_logs (channel_id, created_at DESC);
CREATE INDEX idx_sync_log_merchant ON public.channel_sync_logs (merchant_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- 18. daily_statistics — Daily stats, partitioned by stat_date
-- ---------------------------------------------------------------------------
CREATE TABLE public.daily_statistics (
    id              VARCHAR(20),
    merchant_id     VARCHAR(20)   NOT NULL,
    platform_id     VARCHAR(20)   NOT NULL,
    channel_id      VARCHAR(20)   NOT NULL,
    stat_date       DATE          NOT NULL,
    order_count     INTEGER       DEFAULT 0,
    total_amount    NUMERIC(15,2) DEFAULT 0,
    shipped_count   INTEGER       DEFAULT 0,
    completed_count INTEGER       DEFAULT 0,
    cancelled_count INTEGER       DEFAULT 0,
    refund_count    INTEGER       DEFAULT 0,
    created_at      TIMESTAMPTZ   DEFAULT now(),
    updated_at      TIMESTAMPTZ   DEFAULT now(),
    PRIMARY KEY (id, stat_date)
) PARTITION BY RANGE (stat_date);

CREATE UNIQUE INDEX idx_daily_stats_unique
    ON public.daily_statistics (merchant_id, platform_id, channel_id, stat_date);

-- Monthly partitions for 2026
CREATE TABLE public.daily_statistics_2026_01
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

CREATE TABLE public.daily_statistics_2026_02
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

CREATE TABLE public.daily_statistics_2026_03
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');

CREATE TABLE public.daily_statistics_2026_04
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');

CREATE TABLE public.daily_statistics_2026_05
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');

CREATE TABLE public.daily_statistics_2026_06
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE public.daily_statistics_2026_07
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE public.daily_statistics_2026_08
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE public.daily_statistics_2026_09
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE TABLE public.daily_statistics_2026_10
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

CREATE TABLE public.daily_statistics_2026_11
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');

CREATE TABLE public.daily_statistics_2026_12
    PARTITION OF public.daily_statistics
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- ---------------------------------------------------------------------------
-- 19. failed_task_logs — Kafka failed task logs (independent)
-- ---------------------------------------------------------------------------
CREATE TABLE public.failed_task_logs (
    id              VARCHAR(20)  NOT NULL,
    message_id      VARCHAR(50),
    task_type       VARCHAR(50),
    task_action     VARCHAR(100),
    source_job_type VARCHAR(50),
    merchant_id     VARCHAR(20),
    owner_id        VARCHAR(50),
    original_topic  VARCHAR(100),
    original_key    VARCHAR(200),
    error_message   TEXT,
    reason          VARCHAR(50),
    retry_count     INTEGER      DEFAULT 0,
    payload         JSONB,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_failed_task_created ON public.failed_task_logs (created_at);
CREATE INDEX idx_failed_task_action ON public.failed_task_logs (task_action);
