FROM openjdk:17-jdk-slim as builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y gradle && rm -rf /var/lib/apt/lists/*
RUN gradle -p simpleec-api bootJar

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/simpleec-api/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
