rootProject.name = 'simpleec-oms'

// Shared libraries
include 'simpleec-common'
include 'simpleec-core'
include 'simpleec-channel'

// Boot applications
include 'simpleec-api'
include 'simpleec-gateway'
include 'simpleec-channel-job'
include 'simpleec-order-job'
include 'simpleec-scheduler-job'
include 'simpleec-backend-job'
include 'simpleec-frontend-job'
include 'simpleec-retry-job'
