spring:
  application:
    name: simpleec-backend-job
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleec
    username: simpleec
    password: simpleec123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-job-group
      auto-offset-reset: earliest

server:
  port: 8086

logging:
  level:
    com.simpleec: DEBUG
