spring:
  application:
    name: simpleec-backend-job
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleec
    username: simpleec
    password: simpleec123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: backend-consumer-group
      auto-offset-reset: earliest

server:
  port: 8084

logging:
  level:
    com.simpleec: DEBUG
    com.simpleec.backendJob: DEBUG
    org.springframework.kafka: DEBUG
