spring:
  application:
    name: simpleec-channel-job
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: simpleec-kafka:9092
    consumer:
      group-id: ${JOB_CHANNEL_GROUP_ID:channel-job-group}
      auto-offset-reset: earliest
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 2000
  datasource:
    url: jdbc:postgresql://simpleec-postgres:5432/simpleec
    username: simpleec
    password: simpleec123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    enabled: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.simpleec: DEBUG
