spring:
  application:
    name: simpleec-channel-job
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:simpleec-kafka:9092}
    consumer:
      group-id: ${JOB_CHANNEL_GROUP_ID:channel-job-group}
      auto-offset-reset: earliest
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 0
    timeout: 2000
  jpa:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    com.simpleec: DEBUG
