spring:
  application:
    name: simpleec-channel-job
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: simpleec-kafka:9092
    consumer:
      group-id: channel-job-group
      auto-offset-reset: earliest
  jpa:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

logging:
  level:
    com.simpleec: DEBUG
