dependencies {
    implementation project(':simpleec-common')
    implementation project(':simpleec-core')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.data:spring-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}

bootJar {
    mainClass = 'com.simpleec.api.ApiApplication'
}
