plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':simpleec-common')
    implementation project(':simpleec-core')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.7'

    runtimeOnly 'org.postgresql:postgresql'
}

bootJar {
    archiveFileName = 'simpleec-backend-job.jar'
    mainClass = 'com.simpleec.job.backend.SimpleecBackendJobApplication'
}
