spring:
  application:
    name: simpleec-gateway
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:simpleec-kafka:9092}

server:
  port: 8088

webhook:
  secrets:
    shopify: ${WEBHOOK_SECRET_SHOPIFY:}
    shopee: ${WEBHOOK_SECRET_SHOPEE:}
    easystore: ${WEBHOOK_SECRET_EASYSTORE:}

logging:
  level:
    com.simpleec: DEBUG
