dependencies {
    implementation project(':simpleec-common')

    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MyBatis Plus
    implementation 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.5'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // PostgreSQL
    implementation 'org.postgresql:postgresql:42.7.1'

    // Flyway for database migrations
    implementation 'org.flywaydb:flyway-core:9.22.3'
}
