spring:
  application:
    name: simpleec-api
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleec
    username: simpleec
    password: simpleec123
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: api-consumer-group
      auto-offset-reset: earliest

server:
  port: 8082
  servlet:
    context-path: /api

logging:
  level:
    com.simpleec: DEBUG
    org.springframework.kafka: INFO
