spring:
  application:
    name: simpleec-order-job
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://simpleec-postgres:5432/simpleec
    username: simpleec
    password: ${DB_PASSWORD:simpleec123}
  kafka:
    bootstrap-servers: simpleec-kafka:9092
    consumer:
      group-id: order-job-group
      auto-offset-reset: earliest
    listener:
      ack-mode: manual_immediate
  data:
    redis:
      host: simpleec-redis
      port: 6379

server:
  port: 8085

logging:
  level:
    com.simpleec: DEBUG
