spring:
  datasource:
  flyway:
    enabled: false
    url: jdbc:postgresql://postgres:5432/simpleec
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-job-group
      auto-offset-reset: earliest
  redis:
    host: redis
    port: 6379

server:
  port: 8085

logging:
  level:
    com.simpleec: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
