spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/simpleec
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none  # 只查詢，不驗證或修改 schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    bootstrap-servers: simpleec-kafka:9092
    producer:
      bootstrap-servers: simpleec-kafka:9092
    consumer:
      bootstrap-servers: simpleec-kafka:9092
  redis:
    host: redis
    port: 6379
