spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/simpleec
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
